PROTOCOLOS_CATALOGO = [

    {
        "nome": "ARP",
        "camada": "Enlace",
        "transporte": "N/A",
        "porta_comum": "N/A",
        "funcao": "Mapeia IP (L3) para MAC Address (L2)",
        "seguro": "Não (sujeito a ARP Spoofing)",
        "badge": "🟡 Atenção",
        "badge_color": "warning"
    },
    {
        "nome": "FTP",
        "camada": "Aplicação",
        "transporte": "TCP",
        "porta_comum": "20, 21",
        "funcao": "Transferência de arquivos em texto claro",
        "seguro": "Não",
        "badge": "🔴 Crítico",
        "badge_color": "danger"
    },
    {
        "nome": "FTPS",
        "camada": "Aplicação",
        "transporte": "TCP",
        "porta_comum": "990",
        "funcao": "FTP sobre SSL/TLS",
        "seguro": "Sim",
        "badge": "🟢 Seguro",
        "badge_color": "success"
    },
    {
        "nome": "SFTP",
        "camada": "Aplicação",
        "transporte": "TCP",
        "porta_comum": "22",
        "funcao": "Transferência de arquivos usando subsistema SSH",
        "seguro": "Sim",
        "badge": "🟢 Seguro",
        "badge_color": "success"
    },
    {
        "nome": "TELNET",
        "camada": "Aplicação",
        "transporte": "TCP",
        "porta_comum": "23",
        "funcao": "Terminal virtual remoto",
        "seguro": "Não (texto claro)",
        "badge": "🔴 Crítico",
        "badge_color": "danger"
    },
    {
        "nome": "SSH",
        "camada": "Aplicação",
        "transporte": "TCP",
        "porta_comum": "22",
        "funcao": "Acesso remoto seguro e tunelamento",
        "seguro": "Sim",
        "badge": "🟢 Seguro",
        "badge_color": "success"
    },
    {
        "nome": "POP3",
        "camada": "Aplicação",
        "transporte": "TCP",
        "porta_comum": "110",
        "funcao": "Download de e-mails (não sincroniza)",
        "seguro": "Não",
        "badge": "🔴 Crítico",
        "badge_color": "danger"
    },
    {
        "nome": "IMAP",
        "camada": "Aplicação",
        "transporte": "TCP",
        "porta_comum": "143",
        "funcao": "Sincronização de mensagens no servidor",
        "seguro": "Não",
        "badge": "🔴 Crítico",
        "badge_color": "danger"
    },
    {
        "nome": "NTP",
        "camada": "Aplicação",
        "transporte": "UDP",
        "porta_comum": "123",
        "funcao": "Sincronização de relógios de rede",
        "seguro": "Não por padrão",
        "badge": "🔵 Didático",
        "badge_color": "info"
    },
    {
        "nome": "LDAP",
        "camada": "Aplicação",
        "transporte": "TCP",
        "porta_comum": "389",
        "funcao": "Consulta a serviços de diretório",
        "seguro": "Não (usa texto claro)",
        "badge": "🟡 Atenção",
        "badge_color": "warning"
    },
    {
        "nome": "SMB",
        "camada": "Aplicação",
        "transporte": "TCP",
        "porta_comum": "445",
        "funcao": "Compartilhamento de arquivos (Windows)",
        "seguro": "Requer SMBv3 + criptografia",
        "badge": "🟡 Atenção",
        "badge_color": "warning"
    },
    {
        "nome": "RDP",
        "camada": "Aplicação",
        "transporte": "TCP/UDP",
        "porta_comum": "3389",
        "funcao": "Acesso à área de trabalho remota",
        "seguro": "Sim (se NLA ativo), mas alvo frequente",
        "badge": "🟡 Atenção",
        "badge_color": "warning"
    },
    {
        "nome": "TLS",
        "camada": "Transporte/Sessão",
        "transporte": "TCP",
        "porta_comum": "Múltiplas",
        "funcao": "Segurança e criptografia de ponta a ponta",
        "seguro": "Sim",
        "badge": "🟢 Seguro",
        "badge_color": "success"
    },
    {
        "nome": "QUIC",
        "camada": "Transporte",
        "transporte": "UDP",
        "porta_comum": "443",
        "funcao": "Transporte multiplexado de baixa latência",
        "seguro": "Sim (TLS 1.3 embutido)",
        "badge": "🟢 Seguro",
        "badge_color": "success"
    },
    {
        "nome": "HTTP",
        "camada": "Aplicação",
        "transporte": "TCP",
        "porta_comum": "80",
        "funcao": "Transferência de hipertexto",
        "seguro": "Não",
        "badge": "🔴 Crítico",
        "badge_color": "danger"
    },
    {
        "nome": "HTTPS",
        "camada": "Aplicação",
        "transporte": "TCP",
        "porta_comum": "443",
        "funcao": "HTTP protegido por TLS",
        "seguro": "Sim",
        "badge": "🟢 Seguro",
        "badge_color": "success"
    },
    {
        "nome": "HTTP/3",
        "camada": "Aplicação",
        "transporte": "UDP (via QUIC)",
        "porta_comum": "443",
        "funcao": "Próxima geração da web (mais rápido)",
        "seguro": "Sim",
        "badge": "🟢 Seguro",
        "badge_color": "success"
    },
    {
        "nome": "BGP-4 / eBGP",
        "camada": "Aplicação",
        "transporte": "TCP",
        "porta_comum": "179",
        "funcao": "Entre Sistemas Autônomos (eBGP): políticas, AS-PATH, escolha de rotas na Internet",
        "seguro": "TCP; no mundo real usar RPKI/ROV quando aplicável",
        "badge": "🔵 Didático",
        "badge_color": "info",
        "alcance": "EGP",
        "algoritmo": "Path Vector",
        "metrica": "AS-PATH, LOCAL_PREF, MED, Weight (vendor)",
        "distancia_administrativa": "20 (eBGP)",
        "atualizacao": "Incremental por evento (sessão TCP 179)",
        "sintaxe_base": "router bgp <AS_LOCAL> | neighbor <IP_VIZINHO> remote-as <AS_REMOTO> | network <REDE> mask <MASCARA>",
        "dica_didatica": "EGP moderno na prática = BGP entre AS; orientado a política, não menor custo interno.",
    },
    {
        "nome": "OSPFv2",
        "camada": "Rede",
        "transporte": "IP (Protocolo 89)",
        "porta_comum": "N/A",
        "funcao": "IGP link-state IPv4: áreas OSPF, LSDB, SPF, Router-ID",
        "seguro": "Autenticação MD5/SHA por área/interface",
        "badge": "🔵 Didático",
        "badge_color": "info",
        "alcance": "IGP",
        "algoritmo": "Link-State (SPF / Dijkstra)",
        "metrica": "Cost (baseado em banda)",
        "distancia_administrativa": "110",
        "atualizacao": "LSA por evento + hellos periódicos",
        "sintaxe_base": "router ospf <PROCESS_ID> | network <REDE> <WILDCARD> area <AREA_ID>",
        "dica_didatica": "No OSPF usa-se wildcard na instrução network; backbone é a área 0.",
    },
    {
        "nome": "OSPFv3",
        "camada": "Rede",
        "transporte": "IP (Protocolo 89)",
        "porta_comum": "N/A",
        "funcao": "IGP link-state IPv6 (instâncias por link; suporte AF)",
        "seguro": "Autenticação IPsec ou nativa por interface",
        "badge": "🔵 Didático",
        "badge_color": "info",
        "alcance": "IGP",
        "algoritmo": "Link-State (SPF / Dijkstra)",
        "metrica": "Cost",
        "distancia_administrativa": "110",
        "atualizacao": "LSA por evento + hellos periódicos",
        "sintaxe_base": "ipv6 router ospf <PROCESS_ID> | interface <IF> | ipv6 ospf <PROCESS_ID> area <AREA_ID>",
        "dica_didatica": "No OSPFv3 a ativação costuma ser por interface no IPv6.",
    },
    {
        "nome": "RIPv1",
        "camada": "Aplicação",
        "transporte": "UDP",
        "porta_comum": "520",
        "funcao": "IGP vetor de distância classful (redes por classe); broadcast; hop máx 15",
        "seguro": "Sem autenticação forte",
        "badge": "🔵 Didático",
        "badge_color": "info",
        "alcance": "IGP",
        "algoritmo": "Distance Vector",
        "metrica": "Hop count (máximo 15)",
        "distancia_administrativa": "120",
        "atualizacao": "Periódica (30s)",
        "sintaxe_base": "router rip | network <REDE_CLASSFUL>",
        "dica_didatica": "Classful: não envia máscara, limitado para redes sem VLSM.",
    },
    {
        "nome": "RIPv2",
        "camada": "Aplicação",
        "transporte": "UDP",
        "porta_comum": "520",
        "funcao": "IGP vetor de distância classless (VLSM), multicast 224.0.0.9, campo next-hop",
        "seguro": "MD5 opcional",
        "badge": "🔵 Didático",
        "badge_color": "info",
        "alcance": "IGP",
        "algoritmo": "Distance Vector",
        "metrica": "Hop count (máximo 15)",
        "distancia_administrativa": "120",
        "atualizacao": "Periódica (30s) + triggered updates",
        "sintaxe_base": "router rip | version 2 | network <REDE> | no auto-summary",
        "dica_didatica": "Do PPT: RIP v2 + no auto-summary para cenários classless com VLSM.",
    },
    {
        "nome": "EIGRP",
        "camada": "Rede",
        "transporte": "IP (Protocolo 88)",
        "porta_comum": "N/A",
        "funcao": "IGP híbrido Cisco (DUAL): métrica composta, convergência rápida",
        "seguro": "Autenticação opcional",
        "badge": "🔵 Didático",
        "badge_color": "info",
        "alcance": "IGP",
        "algoritmo": "DUAL (híbrido avançado)",
        "metrica": "Composta (bandwidth + delay; opcional load/reliability)",
        "distancia_administrativa": "90 (interna) / 170 (externa)",
        "atualizacao": "Parcial e por evento",
        "sintaxe_base": "router eigrp <AS> | network <REDE> <WILDCARD> | no auto-summary",
        "dica_didatica": "Convergência rápida via sucessor e feasible successor.",
    },
    {
        "nome": "IGRP",
        "camada": "Rede",
        "transporte": "IP (Protocolo 9)",
        "porta_comum": "N/A",
        "funcao": "IGP vetor de distância Cisco (legado); antecessor do EIGRP",
        "seguro": "Autenticação simples",
        "badge": "🔵 Didático",
        "badge_color": "info",
        "alcance": "IGP",
        "algoritmo": "Distance Vector",
        "metrica": "Composta (bandwidth, delay, load, reliability)",
        "distancia_administrativa": "100",
        "atualizacao": "Periódica (90s)",
        "sintaxe_base": "router igrp <AS> | network <REDE_CLASSFUL>",
        "dica_didatica": "Legado Cisco; substituído por EIGRP em projetos modernos.",
    },
    {
        "nome": "IS-IS",
        "camada": "Rede",
        "transporte": "Enlace (L2) / PDU integrado",
        "porta_comum": "N/A",
        "funcao": "IGP link-state para IPv4 e IPv6 (NI); comum em ISP e backbone",
        "seguro": "Autenticação em adjacências L1/L2",
        "badge": "🔵 Didático",
        "badge_color": "info",
        "alcance": "IGP",
        "algoritmo": "Link-State (SPF)",
        "metrica": "Cost",
        "distancia_administrativa": "115",
        "atualizacao": "LSP por evento + hellos",
        "sintaxe_base": "router isis <TAG> | net <NSAP> | interface <IF> | ip router isis",
        "dica_didatica": "Muito usado em backbone/ISP por robustez e escala.",
    },
    {
        "nome": "iBGP",
        "camada": "Aplicação",
        "transporte": "TCP",
        "porta_comum": "179",
        "funcao": "Mesmo BGP-4, sessão dentro do mesmo AS: reflete prefixos aprendidos por eBGP",
        "seguro": "Políticas de rota + TCP; não é OSPF/EIGRP — complementa IGP interno",
        "badge": "🔵 Didático",
        "badge_color": "info",
        "alcance": "N/A",
        "algoritmo": "Path Vector",
        "metrica": "Políticas BGP (LOCAL_PREF, MED, communities)",
        "distancia_administrativa": "200",
        "atualizacao": "Incremental por evento",
        "sintaxe_base": "router bgp <AS> | neighbor <IP> remote-as <MESMO_AS> | next-hop-self (quando necessário)",
        "dica_didatica": "Dentro do mesmo AS, iBGP normalmente roda junto de um IGP (OSPF/IS-IS/EIGRP).",
    },
    # --- Extras didáticos (expansão do catálogo; revisão conjunta depois) ---
    {
        "nome": "ICMP",
        "camada": "Rede",
        "transporte": "IP (Protocolo 1)",
        "porta_comum": "N/A",
        "funcao": "Controle e diagnóstico IPv4: ping (echo), unreachable, TTL exceeded, MTU discovery",
        "seguro": "Pode ser abusado para reconhecimento; filtrar na borda",
        "badge": "🔵 Didático",
        "badge_color": "info",
    },
    {
        "nome": "ICMPv6",
        "camada": "Rede",
        "transporte": "IPv6 (Next Header 58)",
        "porta_comum": "N/A",
        "funcao": "Equivalente ICMP para IPv6 + vizinhança (NDP: RS/RA, NS/NA)",
        "seguro": "Filtrar tipos sensíveis na borda; RA guard em switches",
        "badge": "🔵 Didático",
        "badge_color": "info",
    },
    {
        "nome": "IPv4",
        "camada": "Rede",
        "transporte": "Enlace (encapsulamento)",
        "porta_comum": "N/A",
        "funcao": "Endereçamento e encaminhamento de pacotes na Internet (fragmentação, TTL, checksum cabeçalho)",
        "seguro": "IPSec/VPN para confidencialidade",
        "badge": "🔵 Didático",
        "badge_color": "info",
    },
    {
        "nome": "IPv6",
        "camada": "Rede",
        "transporte": "Enlace (encapsulamento)",
        "porta_comum": "N/A",
        "funcao": "Sucessor IPv4: endereços 128 bits, extensões de cabeçalho, sem checksum em camada de rede",
        "seguro": "IPsec integrado ao modelo; firewall stateful obrigatório",
        "badge": "🔵 Didático",
        "badge_color": "info",
    },
    {
        "nome": "DHCP",
        "camada": "Aplicação",
        "transporte": "UDP",
        "porta_comum": "67/68 (servidor/cliente)",
        "funcao": "Atribuição dinâmica de IPv4 (lease), máscara, gateway, DNS",
        "seguro": "DHCP Snooping + reconhecimento de servidor autorizado",
        "badge": "🔵 Didático",
        "badge_color": "info",
    },
    {
        "nome": "DHCPv6",
        "camada": "Aplicação",
        "transporte": "UDP",
        "porta_comum": "546/547",
        "funcao": "Stateful DHCPv6 ou combined com SLAAC (flags IA_NA / IA_PD)",
        "seguro": "Autenticação de servidor + segmentação L2",
        "badge": "🔵 Didático",
        "badge_color": "info",
    },
    {
        "nome": "SMTP",
        "camada": "Aplicação",
        "transporte": "TCP",
        "porta_comum": "25",
        "funcao": "Transferência de correio entre MTAs (relay)",
        "seguro": "TLS opcional (STARTTLS); SPF/DKIM/DMARC no domínio",
        "badge": "🟡 Atenção",
        "badge_color": "warning",
    },
    {
        "nome": "SMTP (Submission)",
        "camada": "Aplicação",
        "transporte": "TCP",
        "porta_comum": "587",
        "funcao": "Envio autenticado do cliente de e-mail para o servidor (RFC 6409)",
        "seguro": "STARTTLS + credenciais",
        "badge": "🟢 Seguro",
        "badge_color": "success",
    },
    {
        "nome": "SMTPS",
        "camada": "Aplicação",
        "transporte": "TCP",
        "porta_comum": "465",
        "funcao": "SMTP encapsulado em TLS desde o handshake (implicit TLS)",
        "seguro": "Sim (TLS)",
        "badge": "🟢 Seguro",
        "badge_color": "success",
    },
    {
        "nome": "SNMP",
        "camada": "Aplicação",
        "transporte": "UDP",
        "porta_comum": "161/162",
        "funcao": "Gestão de rede: polling de MIBs, traps de eventos",
        "seguro": "Preferir SNMPv3 (authPriv); v2c comunidades só em mgmt plane",
        "badge": "🟡 Atenção",
        "badge_color": "warning",
    },
    {
        "nome": "STP",
        "camada": "Enlace",
        "transporte": "Ethernet (BPDUs)",
        "porta_comum": "N/A",
        "funcao": "Spanning Tree IEEE 802.1D: previne loops em switches",
        "seguro": "BPDU Guard / Root Guard em portas de acesso",
        "badge": "🔵 Didático",
        "badge_color": "info",
    },
    {
        "nome": "RSTP",
        "camada": "Enlace",
        "transporte": "Ethernet (BPDUs)",
        "porta_comum": "N/A",
        "funcao": "Rapid Spanning Tree (802.1w): convergência mais rápida que STP clássico",
        "seguro": "Mesmo endurecimento que STP",
        "badge": "🔵 Didático",
        "badge_color": "info",
    },
    {
        "nome": "LACP",
        "camada": "Enlace",
        "transporte": "Ethernet (LACP PDUs)",
        "porta_comum": "N/A",
        "funcao": "802.3ad: agregação de links (port-channel) com negociação",
        "seguro": "Static mode onde política exige previsibilidade",
        "badge": "🔵 Didático",
        "badge_color": "info",
    },
    {
        "nome": "LLDP",
        "camada": "Enlace",
        "transporte": "Ethernet",
        "porta_comum": "N/A",
        "funcao": "Descoberta de vizinhos L2/L3 padrão IEEE 802.1AB (multi-vendor)",
        "seguro": "Filtrar exposição em redes sensíveis",
        "badge": "🔵 Didático",
        "badge_color": "info",
    },
    {
        "nome": "CDP",
        "camada": "Enlace",
        "transporte": "Ethernet (proprietário Cisco)",
        "porta_comum": "N/A",
        "funcao": "Descoberta de vizinhos Cisco; inventário de equipamentos",
        "seguro": "Desativar em portas de cliente/DMZ",
        "badge": "🔵 Didático",
        "badge_color": "info",
    },
    {
        "nome": "NAT",
        "camada": "Rede",
        "transporte": "N/A (função em router/firewall)",
        "porta_comum": "N/A",
        "funcao": "Tradução endereços privados↔públicos (SNAT/DNAT, PAT)",
        "seguro": "Stateful firewall + logs",
        "badge": "🔵 Didático",
        "badge_color": "info",
    },
    {
        "nome": "IPsec",
        "camada": "Rede",
        "transporte": "ESP/AH (IP prot 50/51)",
        "porta_comum": "UDP 500/4500 (IKE)",
        "funcao": "VPN site-to-site ou remote access: confidencialidade e integridade",
        "seguro": "Sim (quando bem configurado IKE/esp)",
        "badge": "🟢 Seguro",
        "badge_color": "success",
    },
    {
        "nome": "WireGuard",
        "camada": "Rede",
        "transporte": "UDP",
        "porta_comum": "51820",
        "funcao": "VPN moderna: crypto noise protocol, menos superfície que IPsec clássico",
        "seguro": "Sim (design minimalista)",
        "badge": "🟢 Seguro",
        "badge_color": "success",
    },
    {
        "nome": "MQTT",
        "camada": "Aplicação",
        "transporte": "TCP",
        "porta_comum": "1883 / 8883",
        "funcao": "Pub/sub IoT leve (broker); TLS tipicamente na 8883",
        "seguro": "TLS + auth forte em ambientes produtivos",
        "badge": "🟡 Atenção",
        "badge_color": "warning",
    },
    {
        "nome": "CoAP",
        "camada": "Aplicação",
        "transporte": "UDP",
        "porta_comum": "5683/5684",
        "funcao": "REST sobre UDP para dispositivos restritos (RFC 7252)",
        "seguro": "DTLS (CoAPS)",
        "badge": "🔵 Didático",
        "badge_color": "info",
    },
    {
        "nome": "DNS",
        "camada": "Aplicação",
        "transporte": "UDP/TCP",
        "porta_comum": "53",
        "funcao": "Resolução de nomes",
        "seguro": "Não por padrão (usar DNSSEC/DoH)",
        "badge": "🟡 Atenção",
        "badge_color": "warning",
    },
]
